package example;


/**
* example/fibonacciHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/dev/workspace1902/repos/corba/CorbaFiboInterface/src/fibonacci.idl
* lunes 12 de julio de 2021 05:48:49 PM CDT
*/

abstract public class fibonacciHelper
{
  private static String  _id = "IDL:example/fibonacci:1.0";

  public static void insert (org.omg.CORBA.Any a, example.fibonacci that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static example.fibonacci extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (example.fibonacciHelper.id (), "fibonacci");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static example.fibonacci read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_fibonacciStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, example.fibonacci value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static example.fibonacci narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof example.fibonacci)
      return (example.fibonacci)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      example._fibonacciStub stub = new example._fibonacciStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static example.fibonacci unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof example.fibonacci)
      return (example.fibonacci)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      example._fibonacciStub stub = new example._fibonacciStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
