package example;


/**
* example/fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/dev/workspace1902/repos/corba/CorbaFiboInterface/src/fibonacci.idl
* lunes 12 de julio de 2021 05:48:49 PM CDT
*/

public interface fibonacci extends fibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface fibonacci
