package example;


/**
* example/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/dev/workspace1902/repos/corba/CorbaFiboInterface/src/fibonacci.idl
* lunes 19 de julio de 2021 05:22:49 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
