package example;


/**
* example/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/dev/workspace1902/repos/corba/CorbaFiboInterface/src/fibonacci.idl
* lunes 19 de julio de 2021 05:22:49 PM CDT
*/

public interface FibonacciOperations 
{

  /* Codigo fibonacci CORBA
  		* in: el valor del parametro se le envia el
  		* cliente al servidor
  		* long: -231...231-1 (32bits)
  		* numero: nombre de la variable
  		*/
  String generar (int numero);
} // interface FibonacciOperations
